package dropTable;

import java.util.Hashtable;

//Drop table for a game, should be contained within game. Should contain hashtables for all other itmes.
public class DropTable
{
	//This one is a bit confusing, we have a hashtable which contains ALL other tables used for loot.
	//We need their keys and values too, as well as the "godTable's" value which will be generated by RNG.
	private Hashtable<Hashtable<Item,Integer>,Integer>godTable = new Hashtable<Hashtable<Item,Integer>,Integer>();
	
}
